import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./StaticComponents/Header";
import Footer from "./StaticComponents/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
              <Header />
              <div className="flex-auto">
                <div className="mx-auto w-full max-w-7xl lg:px-8">
                  {children}
                </div>
              </div>
          <Footer />
      </body>
    </html>
  );
}
